create table if not exists public.likes_anon (
  id bigint generated by default as identity primary key,
  item_id text not null,
  device_id text not null,
  created_at timestamptz not null default now(),
  unique (item_id, device_id)
);

create index if not exists likes_anon_item_id_idx on public.likes_anon (item_id);
create index if not exists likes_anon_device_id_idx on public.likes_anon (device_id);

alter table public.likes_anon enable row level security;

create or replace function public.request_device_id()
returns text
language sql
stable
as $$
  select coalesce(
    (current_setting('request.headers', true)::json->>'x-device-id'),
    ''
  );
$$;

create policy "likes_anon_select_all"
on public.likes_anon
for select
to anon, authenticated
using (true);

create policy "likes_anon_insert_match_device"
on public.likes_anon
for insert
to anon, authenticated
with check (device_id = public.request_device_id());

create policy "likes_anon_delete_match_device"
on public.likes_anon
for delete
to anon, authenticated
using (device_id = public.request_device_id());
