version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "security"
      - "ci/cd"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
      - "ci/cd"
    commit-message:
      prefix: "chore"
      include: "scope"
