begin;

create table if not exists public.likes_anon (
  id bigint generated by default as identity primary key,
  item_id text not null check (char_length(item_id) between 1 and 120),
  device_id text not null check (char_length(device_id) between 8 and 128),
  created_at timestamptz not null default now(),
  unique (item_id, device_id)
);

create table if not exists public.ratings_anon (
  id bigint generated by default as identity primary key,
  item_id text not null check (char_length(item_id) between 1 and 120),
  device_id text not null check (char_length(device_id) between 8 and 128),
  stars smallint not null check (stars between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (item_id, device_id)
);

create index if not exists likes_anon_item_id_idx on public.likes_anon (item_id);
create index if not exists ratings_anon_item_id_idx on public.ratings_anon (item_id);

create or replace view public.ratings_summary as
select
  item_id,
  round(avg(stars)::numeric, 2) as avg_stars,
  count(*)::bigint as ratings_count
from public.ratings_anon
group by item_id;

create or replace function public.request_device_id()
returns text
language sql
stable
set search_path = public, pg_temp
as $$
  select coalesce(current_setting('request.headers', true)::json ->> 'x-device-id', '');
$$;

create or replace function public.assert_request_device_id(p_device_id text)
returns void
language plpgsql
stable
set search_path = public, pg_temp
as $$
begin
  if p_device_id is null
     or char_length(p_device_id) not between 8 and 128
     or public.request_device_id() <> p_device_id then
    raise exception 'invalid device identity' using errcode = '42501';
  end if;
end;
$$;

create or replace function public.toggle_like_anon(p_item_id text, p_device_id text)
returns table(liked boolean, likes bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.assert_request_device_id(p_device_id);
  if p_item_id is null or char_length(p_item_id) not between 1 and 120 then
    raise exception 'invalid item id' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_device_id || ':' || p_item_id, 0));

  delete from public.likes_anon
  where item_id = p_item_id and device_id = p_device_id;

  if found then
    liked := false;
  else
    insert into public.likes_anon(item_id, device_id)
    values (p_item_id, p_device_id)
    on conflict (item_id, device_id) do nothing;
    liked := true;
  end if;

  select count(*) into likes from public.likes_anon where item_id = p_item_id;
  return next;
end;
$$;

create or replace function public.upsert_rating_anon(p_item_id text, p_device_id text, p_stars integer)
returns table(average numeric, votes bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.assert_request_device_id(p_device_id);
  if p_stars not between 1 and 5 then
    raise exception 'invalid stars' using errcode = '22023';
  end if;

  insert into public.ratings_anon(item_id, device_id, stars)
  values (p_item_id, p_device_id, p_stars::smallint)
  on conflict (item_id, device_id)
  do update set stars = excluded.stars, updated_at = now();

  select round(avg(stars)::numeric, 2), count(*)
  into average, votes
  from public.ratings_anon
  where item_id = p_item_id;
  return next;
end;
$$;

create or replace function public.remove_rating_anon(p_item_id text, p_device_id text)
returns table(average numeric, votes bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform public.assert_request_device_id(p_device_id);
  delete from public.ratings_anon where item_id = p_item_id and device_id = p_device_id;

  select coalesce(round(avg(stars)::numeric, 2), 0), count(*)
  into average, votes
  from public.ratings_anon
  where item_id = p_item_id;
  return next;
end;
$$;

alter table public.likes_anon enable row level security;
alter table public.ratings_anon enable row level security;

drop policy if exists likes_anon_insert_match_device on public.likes_anon;
drop policy if exists likes_anon_delete_match_device on public.likes_anon;
drop policy if exists ratings_anon_insert_match_device on public.ratings_anon;
drop policy if exists ratings_anon_update_match_device on public.ratings_anon;
drop policy if exists ratings_anon_delete_match_device on public.ratings_anon;

drop policy if exists likes_anon_select_all on public.likes_anon;
create policy likes_anon_select_all on public.likes_anon for select to anon, authenticated using (true);

drop policy if exists ratings_anon_select_all on public.ratings_anon;
create policy ratings_anon_select_all on public.ratings_anon for select to anon, authenticated using (true);

revoke all on function public.toggle_like_anon(text, text) from public;
revoke insert, update, delete, truncate, references, trigger on public.likes_anon from anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.ratings_anon from anon, authenticated;
grant select on public.likes_anon, public.ratings_anon, public.ratings_summary to anon, authenticated;

revoke all on function public.upsert_rating_anon(text, text, integer) from public;
revoke all on function public.remove_rating_anon(text, text) from public;
grant execute on function public.toggle_like_anon(text, text) to anon, authenticated;
grant execute on function public.upsert_rating_anon(text, text, integer) to anon, authenticated;
grant execute on function public.remove_rating_anon(text, text) to anon, authenticated;

commit;
